name: xfdm
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  go_router: ^13.2.0
  window_manager: ^0.3.2
  fluent_ui: ^4.8.6
  flutter_acrylic: ^1.1.0
  rust_lib_xfdm:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.31
  device_info_plus: ^9.0.3
  synchronized: ^3.1.0+1
  aria2:
    git: https://github.com/xkeyC/dart_aria2_rpc.git
  # path: ../../xkeyC/dart_aria2_rpc
  hive: ^2.2.3
  archive: ^3.4.10
  path_provider: ^2.1.1
  file_sizes: ^1.0.6
  desktop_drop: ^0.4.4
  file_picker: ^8.0.0+1
  local_hero: ^0.3.0
  path: ^1.9.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  ffigen: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/binary/
flutter_intl:
  enabled: true
